### PR TITLE
[For Review]: Added initial files for git section of guidelines

### PR DESCRIPTION
**Pull request by kbacalso**
* Added git folder to contain all git related pages
* Added undoing-committed-work.md. Added intro and amend guidlines.

### CODE REVIEW

**Comment by cgosingtian** [comment]
We may need a note on how to use the terminal text editor somewhere... maybe even just a link to a resource online would work?

**Comment by kbacalso** [comment]
@cgosingtian noted 👍  maybe I'll add a link somewhere for git basics on the terminal. I was also thinking of creating another page for an overview of the git section. And then maybe just mention there that the articles will mention both ways for the terminal and sourcetree. whatcha think?

**Comment by cgosingtian** [comment]
I'm thinking it would be better to stick to one option; having both options (terminal, GUI) increases the possibility of someone diverging from standard (either wilfully or by error).

I'm more keen on GUI myself; while terminal is more direct and allows more control, the very limits that a GUI imposes lets us reduce the number of possible complications. I'd like to propose officially using a GUI (Sourcetree still looks good for our needs, unless you have something specific in mind that can only be done in terminal). The knowledge of using git in terminal can be used for custom things in the rarest of occasions.

**Comment by cgosingtian** [comment]
Looks good to me! (OT: In your suggested "How to" section, we may need to list down our standard operating procedures considering that we're mostly explaining how to do things but without context. On that note maybe we can just name "How to" to "Standard Operating Procedures"?)

**Comment by ericacaber** [comment]
👍

**Pull request merged**
